# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .arrival import Arrival
from .arrival_board import ArrivalBoard
from .color import Color
from .coord_location import CoordLocation
from .creation_date import CreationDate
from .date_begin import DateBegin
from .date_end import DateEnd
from .departure import Departure
from .departure_board import DepartureBoard
from .destination import Destination
from .direction import Direction
from .geometry import Geometry
from .geometry_ref import GeometryRef
from .journey_detail import JourneyDetail
from .journey_detail_ref import JourneyDetailRef
from .journey_id import JourneyId
from .journey_name import JourneyName
from .journey_type import JourneyType
from .leg import Leg
from .live_map import LiveMap
from .location_list import LocationList
from .note import Note
from .notes import Notes
from .origin import Origin
from .point import Point
from .points import Points
from .stop import Stop
from .stop_location import StopLocation
from .system_info import SystemInfo
from .time_table_data import TimeTableData
from .time_table_period import TimeTablePeriod
from .timetable_info import TimetableInfo
from .trip import Trip
from .trip_list import TripList
from .vehicle import Vehicle
