# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TimetableInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time_table_data': 'TimeTableData',
        'time_table_period': 'TimeTablePeriod'
    }

    attribute_map = {
        'time_table_data': 'TimeTableData',
        'time_table_period': 'TimeTablePeriod'
    }

    def __init__(self, time_table_data=None, time_table_period=None):
        """
        TimetableInfo - a model defined in Swagger
        """

        self._time_table_data = None
        self._time_table_period = None

        self.time_table_data = time_table_data
        self.time_table_period = time_table_period

    @property
    def time_table_data(self):
        """
        Gets the time_table_data of this TimetableInfo.

        :return: The time_table_data of this TimetableInfo.
        :rtype: TimeTableData
        """
        return self._time_table_data

    @time_table_data.setter
    def time_table_data(self, time_table_data):
        """
        Sets the time_table_data of this TimetableInfo.

        :param time_table_data: The time_table_data of this TimetableInfo.
        :type: TimeTableData
        """
        if time_table_data is None:
            raise ValueError("Invalid value for `time_table_data`, must not be `None`")

        self._time_table_data = time_table_data

    @property
    def time_table_period(self):
        """
        Gets the time_table_period of this TimetableInfo.

        :return: The time_table_period of this TimetableInfo.
        :rtype: TimeTablePeriod
        """
        return self._time_table_period

    @time_table_period.setter
    def time_table_period(self, time_table_period):
        """
        Sets the time_table_period of this TimetableInfo.

        :param time_table_period: The time_table_period of this TimetableInfo.
        :type: TimeTablePeriod
        """
        if time_table_period is None:
            raise ValueError("Invalid value for `time_table_period`, must not be `None`")

        self._time_table_period = time_table_period

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TimetableInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
