# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TimeTablePeriod(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date_begin': 'DateBegin',
        'date_end': 'DateEnd'
    }

    attribute_map = {
        'date_begin': 'DateBegin',
        'date_end': 'DateEnd'
    }

    def __init__(self, date_begin=None, date_end=None):
        """
        TimeTablePeriod - a model defined in Swagger
        """

        self._date_begin = None
        self._date_end = None

        self.date_begin = date_begin
        self.date_end = date_end

    @property
    def date_begin(self):
        """
        Gets the date_begin of this TimeTablePeriod.

        :return: The date_begin of this TimeTablePeriod.
        :rtype: DateBegin
        """
        return self._date_begin

    @date_begin.setter
    def date_begin(self, date_begin):
        """
        Sets the date_begin of this TimeTablePeriod.

        :param date_begin: The date_begin of this TimeTablePeriod.
        :type: DateBegin
        """
        if date_begin is None:
            raise ValueError("Invalid value for `date_begin`, must not be `None`")

        self._date_begin = date_begin

    @property
    def date_end(self):
        """
        Gets the date_end of this TimeTablePeriod.

        :return: The date_end of this TimeTablePeriod.
        :rtype: DateEnd
        """
        return self._date_end

    @date_end.setter
    def date_end(self, date_end):
        """
        Sets the date_end of this TimeTablePeriod.

        :param date_end: The date_end of this TimeTablePeriod.
        :type: DateEnd
        """
        if date_end is None:
            raise ValueError("Invalid value for `date_end`, must not be `None`")

        self._date_end = date_end

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TimeTablePeriod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
