# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.geometry_api import GeometryApi


class TestGeometryApi(unittest.TestCase):
    """ GeometryApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.geometry_api.GeometryApi()

    def tearDown(self):
        pass

    def test_get_geometry(self):
        """
        Test case for get_geometry

        Returns the polyline for a leg.
        """
        pass


if __name__ == '__main__':
    unittest.main()
