# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.journey_detail_api import JourneyDetailApi


class TestJourneyDetailApi(unittest.TestCase):
    """ JourneyDetailApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.journey_detail_api.JourneyDetailApi()

    def tearDown(self):
        pass

    def test_get_journey_detail(self):
        """
        Test case for get_journey_detail

        Returns information about the complete route of a trip.
        """
        pass


if __name__ == '__main__':
    unittest.main()
