# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.arrival_board_api import ArrivalBoardApi


class TestArrivalBoardApi(unittest.TestCase):
    """ ArrivalBoardApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.arrival_board_api.ArrivalBoardApi()

    def tearDown(self):
        pass

    def test_get_arrival_board(self):
        """
        Test case for get_arrival_board

        Return the next 20 arrivals (or less if not existing) from a given point in time or the next arrivals in a given timespan.
        """
        pass


if __name__ == '__main__':
    unittest.main()
