# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.stop_location import StopLocation


class TestStopLocation(unittest.TestCase):
    """ StopLocation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStopLocation(self):
        """
        Test StopLocation
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.stop_location.StopLocation()
        pass


if __name__ == '__main__':
    unittest.main()
