# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.departure_board_api import DepartureBoardApi


class TestDepartureBoardApi(unittest.TestCase):
    """ DepartureBoardApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.departure_board_api.DepartureBoardApi()

    def tearDown(self):
        pass

    def test_get_departure_board(self):
        """
        Test case for get_departure_board

        Return the next 20 departures (or less if not existing) from a given point in time or the next departures in a given timespan.
        """
        pass


if __name__ == '__main__':
    unittest.main()
