# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.trip_api import TripApi


class TestTripApi(unittest.TestCase):
    """ TripApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.trip_api.TripApi()

    def tearDown(self):
        pass

    def test_get_trip(self):
        """
        Test case for get_trip

        Calculates a trip from a specified origin to a specified destination.
        """
        pass


if __name__ == '__main__':
    unittest.main()
