# coding: utf-8

"""
    Reseplaneraren

    Provides access to Västtrafik journey planner

    OpenAPI spec version: 1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.location_api import LocationApi


class TestLocationApi(unittest.TestCase):
    """ LocationApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.location_api.LocationApi()

    def tearDown(self):
        pass

    def test_get_all_stops(self):
        """
        Test case for get_all_stops

        Returns a list of all stops available in the journey planner.
        """
        pass

    def test_get_location_by_name(self):
        """
        Test case for get_location_by_name

        Returns a list of possible matches in the journey planner database
        """
        pass

    def test_get_nearby_address(self):
        """
        Test case for get_nearby_address

        Returns the address nearest a given coordinate.
        """
        pass

    def test_get_nearby_stops(self):
        """
        Test case for get_nearby_stops

        Returns a list of stops around a given center coordinate.
        """
        pass


if __name__ == '__main__':
    unittest.main()
